### ISSUE TITLE
Typed results for minimal APIs

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs.Samples#10]
See [Typed results for minimal APIs](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#typed-results-for-minimal-apis)

It would be great to have the sample from that blog here. You can get the starter project code from https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/first-web-api/samples/6.0/TodoApi

Create your new project in a new folder `typed-results`  under `https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples`

See tests in https://github.com/dotnet/aspnetcore/tree/main/src/Mvc/Mvc.ApiExplorer/test

cc @sammychinedu2ky if you're interested.

`@brunolins16` is the expert on this. See https://github.com/dotnet/aspnetcore/issues/40656

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky  looks like this is done

- https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#typed-results
- https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-6.0#typed-results-for-minimal-apis

**Comment by sammychinedu2ky** [comment]
> @sammychinedu2ky looks like this is done
> 
> * https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#typed-results
> * https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-6.0#typed-results-for-minimal-apis

Fresh
