### ISSUE TITLE
Rate limiter provides no feedback when limit is hit

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs.Samples#100]
Consider the following code:

```
using Microsoft.AspNetCore.RateLimiting;
using System.Threading.RateLimiting;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddRateLimiter(_ => _
    .AddFixedWindowLimiter(policyName: "fixed", options =>
    {
        options.PermitLimit = 4;
        options.Window = TimeSpan.FromSeconds(120);
        options.QueueProcessingOrder = QueueProcessingOrder.OldestFirst;
        options.QueueLimit = 2;
    }));

var app = builder.Build();

app.UseRateLimiter();

static string GetTicks() => (DateTime.Now.Ticks & 0x11111).ToString("00000");

app.MapGet("/", () => Results.Ok($"Hello {GetTicks()}"))
                           .RequireRateLimiting("fixed");

app.Run();
```

Browse to `/` on localhost and quickly hit refresh multiple times. After the rate limit is hit, the browser doesn't show a problem, it's displaying the last response. F12 tools don't show any thing and there is nothing in the log.

@wtgodbe how can the client be notified? What's the best way to log this? Why isn't the default rejection status 503 returned?
cc @fiyazbinhasan

**Comment by wtgodbe** [comment]
CC @BrennanConroy - I believe the problem is the 5th request will be sitting in the queue until it can be granted a permit. If a separate connection where to send a request, it'd be the 2nd in the queue, then a 3rd connection sending a request would get rejected. `QueueLimit` would need to be `0` for the 5th request to get rejected immediately. CC @BrennanConroy

**Comment by Rick-Anderson** [comment]
> CC @BrennanConroy - I believe the problem is the 5th request will be sitting in the queue until it can be granted a permit. If a separate connection were to send a request, it'd be the 2nd in the queue, then a 3rd connection sending a request would get rejected. `QueueLimit` would need to be `0` for the 5th request to get rejected immediately.

I'll test this with Azure load testing and I'll make a note when testing with localhost use multiple browsers. I'm getting 503 on the 2nd browser after the limit/que is maxed out.

Is there any way enable logging for when the limit is hit?

**Comment by Rick-Anderson** [comment]
@wtgodbe on first failure on chrome F12 I get (canceled)
<img width="442" alt="image" src="https://user-images.githubusercontent.com/3605364/195718310-c921fb75-7480-49e1-8a4c-2c354421d06c.png">

But there's no response so no helpful information.

**Comment by wtgodbe** [comment]
This is the only logging we do from the middleware today:

https://github.com/dotnet/aspnetcore/blob/4faa84c9ddf8c9e9cc9e5b43ca15f090037c4b68/src/Middleware/RateLimiting/src/RateLimitingMiddleware.cs#L245-L255

**Comment by BrennanConroy** [comment]
Is that failure because you pressed F5 before the request could complete? That would then be a client-side cancellation and has nothing to do with the middleware.

**Comment by Rick-Anderson** [comment]
Two browsers and `"Microsoft.AspNetCore.RateLimiting":"Debug"` in appsettings.Development.json solves all the localhost testing problem.

Is there a way to apply a limiter to a Razor Page, specific controller, or per action?

**Comment by BrennanConroy** [comment]
Yes, there is `EnableRateLimitingAttribute`, looks like the docs don't even talk about it 😢 should probably update that.

**Comment by Rick-Anderson** [comment]
> Yes, there is `EnableRateLimitingAttribute`, looks like the docs don't even talk about it 😢 should probably update that.

Adding for RP and controllers. Is the following code OK (at controller and action level)?

```
[EnableRateLimitingAttribute("fixed")]
public class Home2Controller : Controller
{
    private readonly ILogger<Home2Controller> _logger;

    public Home2Controller(ILogger<Home2Controller> logger)
    {
        _logger = logger;
    }

    public ContentResult Index()
    {
        return Content("Home2 index");
    }

    [EnableRateLimitingAttribute("sliding")]
    public ContentResult Privacy()
    {
        return Content("No data collected");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}
```

**Comment by BrennanConroy** [comment]
I believe so, from my understanding that means that by default actions will have the "fixed" limiter policy applied. The `Privacy` action will have the "sliding" policy. You can also add `[DisableRateLimiting]` to an action to not have it limited if there is one at the controller level.

**Comment by wtgodbe** [comment]
> I believe so, from my understanding that means that by default actions will have the "fixed" limiter policy applied. The Privacy action will have the "sliding" policy. You can also add [DisableRateLimiting] to an action to not have it limited if there is one at the controller level.

Yep, all correct
