### ISSUE TITLE
Which license applies to the examples?

### ISSUE THREAD

**Issue by HofmeisterAn** [dotnet/AspNetCore.Docs.Samples#136]
Could you please provide the license information for your examples? We are uncertain which license applies to the examples and would appreciate it if you could add the relevant license information to the repository. Additionally, we would like to confirm if it is permissible to use the examples (e.g. test/integration-tests/IntegrationTestsSample) in our own public repository. Thank you.

**Comment by Rick-Anderson** [comment]
@HofmeisterAn  thanks for opening this issue. The license files have been added.

**Comment by HofmeisterAn** [comment]
Thank you for addressing it so quickly.
