### ISSUE TITLE
write sample using service for rate limit

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs.Samples#14]
Use a [service](https://github.com/dotnet/aspnetcore/blob/4cf483ee7a1cb470b8b2290a174ad34f450a5eab/src/Middleware/RateLimiting/src/RateLimiterServiceCollectionExtensions.cs#L20) per https://github.com/dotnet/AspNetCore.Docs.Samples/pull/13#discussion_r949657927

Put the code in [this folder](https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/middleware/rate-limit/ratelimit-service#readme) and delete the `readme.md`.

**Comment by Rick-Anderson** [comment]
@Kahbazi can you do this issue?

**Comment by Rick-Anderson** [comment]
[IServiceCollection AddRateLimiter](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/RateLimiting/src/RateLimiterServiceCollectionExtensions.cs#L20) won't be available until the next release.

**Comment by Kahbazi** [comment]
I didn't quite understand the purpose of this issue. We could update some samples in https://github.com/dotnet/AspNetCore.Docs.Samples/blob/257f38f079bd0dd41824a6ef452a6ce838ecdb04/fundamentals/middleware/rate-limit/WebRateLimitAuth/Program.cs to use `AddRateLimiter` instead of passing the options to the middleware. 

Do we need to write new samples just for using `AddRateLimiter`??

I suggest we update all samples to use `AddRateLimiter` which might be the most use case. Then add one sample with two app.UseRateLimitingMiddleware with different options and every middleware in a different place in pipeline.

**Comment by Rick-Anderson** [comment]
Per [this comment](https://github.com/dotnet/AspNetCore.Docs.Samples/pull/13#discussion_r949659464), add sample code with attribute

> We're removing `AddNoLimiter` in rc1 (we are also adding an attribute that allows you to disable rate limiting entirely for an endpoint, including the global limiter)

**Comment by Rick-Anderson** [comment]
@Kahbazi  Use a [service](https://github.com/dotnet/aspnetcore/blob/4cf483ee7a1cb470b8b2290a174ad34f450a5eab/src/Middleware/RateLimiting/src/RateLimiterServiceCollectionExtensions.cs#L20) per https://github.com/dotnet/AspNetCore.Docs.Samples/pull/13#discussion_r949657927

> Long term I'd prefer using `AddRateLimiter` w/ services: https://github.com/dotnet/aspnetcore/blob/4cf483ee7a1cb470b8b2290a174ad34f450a5eab/src/Middleware/RateLimiting/src/RateLimiterServiceCollectionExtensions.cs#L20


So just rewrite the code so it's not using [`app.UseRateLimiter(new RateLimiterOptions()`](https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/middleware/rate-limit/WebRateLimitAuth/Program.cs#L13)
but using it as service

Would you be able to update all the code to use the service approach? Wasn't that the intention of the comment? Do you think that's a better approach?

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan @Elfocrash @sammychinedu2ky @martincostello are you interested in changing the sample to use `AddRateLimiter`? 

Use a [service](https://github.com/dotnet/aspnetcore/blob/4cf483ee7a1cb470b8b2290a174ad34f450a5eab/src/Middleware/RateLimiting/src/RateLimiterServiceCollectionExtensions.cs#L20) per https://github.com/dotnet/AspNetCore.Docs.Samples/pull/13#discussion_r949657927

> Long term I'd prefer using `AddRateLimiter` w/ services: https://github.com/dotnet/aspnetcore/blob/4cf483ee7a1cb470b8b2290a174ad34f450a5eab/src/Middleware/RateLimiting/src/RateLimiterServiceCollectionExtensions.cs#L20

**Comment by fiyazbinhasan** [comment]
I would like to take a look at it if no one has already started. However, the current sample is not runnable. I'll try to fix it along the way.

**Comment by Rick-Anderson** [comment]
> I would like to take a look at it if no one has already started. However, the current sample is not runnable. I'll try to fix it along the way.

Thanks, it's all yours.

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan when you do the update, can you add the following class:

``` c#
public class SampleProblemDetailsWriter : IProblemDetailsWriter
{
    public bool CanWrite(ProblemDetailsContext context)
        => context.HttpContext.Response.StatusCode == 400;

    public ValueTask WriteAsync(ProblemDetailsContext context)
    {
        //Additional customizations

        // Write to the response
        return new ValueTask(context.HttpContext.Response.WriteAsJsonAsync(context.ProblemDetails));
    }
}
```

From [this comment](https://github.com/dotnet/AspNetCore.Docs.Samples/issues/34#issuecomment-1274577651)
