### ISSUE TITLE
Remove unnecessary code from RDG samples

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs.Samples#201]
See [this comment](https://github.com/dotnet/AspNetCore.Docs.Samples/pull/200#pullrequestreview-1651271512)

```
[JsonSerializable(typeof(Todo[]))]
internal partial class AppJsonSerializerContext : JsonSerializerContext
```

And more can likely be removed from many of [these samples](https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/aot/diagnostics)

cc @timdeschryver

**Comment by timdeschryver** [comment]
I can pick this one up if you want @Rick-Anderson

**Comment by timdeschryver** [comment]
It seems like some examples don't have aot enabled (`<PublishAot>true</PublishAot>`), which explains the different behavior in the examples.

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-7.0#request-delegate-generator

> The RDG is enabled automatically in a project when publishing with native AOT is enabled. RDG can be manually enabled even when not using native AOT by setting <EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator> in the project file. This can be useful when initially evaluating a project's readiness for native AOT, or to reduce the startup time of an app.

@Rick-Anderson which way do you want to take with the examples, or maybe this is OK? 
Once this is cleared out I can go through the examples if you want.
