### ISSUE TITLE
problem details service from middleware

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs.Samples#33]
Create sample that generates a [ problem details response](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-7/#new-problem-details-service)  from middleware:

@sammychinedu2ky are you interested in this?

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/AspNetCore.Docs.Samples/blob/b07d2c5805b90bb7bd91fca50d8ad7d56bc8d55e/fundamentals/middleware/problem-details-service/Program.cs#L35-L42 is probably enough. What do you think @sammychinedu2ky

**Comment by sammychinedu2ky** [comment]
I could still express it's feature by converting the previous sample code
to use a middle instead of the service configuration.

Should I work on that? And if so Which folder location should I use? @Rick
Anderson (ASP.NET) ***@***.***>  😅

**Comment by Rick-Anderson** [comment]
See https://github.com/dotnet/AspNetCore.Docs.Samples/pull/35

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky I'm going to be updating the sample until you're ready to work on it. Just let me know.

**Comment by sammychinedu2ky** [comment]
I would work on it today @Rick-Anderson

**Comment by Rick-Anderson** [comment]
Fixed in #38
