### ISSUE TITLE
Create samples for Route groups with MapGroup 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs.Samples#50]
Need dedicated sample for Route groups with MapGroup 
@sammychinedu2ky can you create a PR here with your code from https://github.com/dotnet/AspNetCore.Docs/issues/26476 so we have code dedicated to route groups. I think maintaining the same code for testing and routegroups might be a problem.

Create a folder `routeGroups` under https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples

**Comment by sammychinedu2ky** [comment]
ok

**Comment by Rick-Anderson** [comment]
Fixed in [ #27034](https://github.com/dotnet/AspNetCore.Docs/pull/27034) right @sammychinedu2ky ?

**Comment by sammychinedu2ky** [comment]
> Fixed in [ #27034](https://github.com/dotnet/AspNetCore.Docs/pull/27034) right @sammychinedu2ky ?

Yh

**Comment by Rick-Anderson** [comment]
[Yh ?](https://www.urbandictionary.com/define.php?term=Yh)

**Comment by sammychinedu2ky** [comment]
Fixed
