### ISSUE TITLE
Self-describing minimal APIs with IEndpointMetadataProvider and IEndpointParameterMetadataProvider

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs.Samples#76]
Create sample code. See https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/

Possibly same code can do dotnet/sdk#77

**Comment by sammychinedu2ky** [comment]
Alright, @Rick-Anderson.
Please where should it be located

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson I noticed a little error, but I'm not sure of the right place to open the issue.
Port 5060 and 5061 aren't allowed by new browser versions due to the [natslip attack ](https://chromestatus.com/feature/5064283639513088).  Port 5060 was randomly created for me in the LaunchSettings.json file which made me have issues accessing my API from the browser. I had to manually change the `applicationUrl` port

**Comment by Rick-Anderson** [comment]
@Tratcher where should this be reported?

**Comment by sammychinedu2ky** [comment]
> @Tratcher where should this be reported?

Please @Tratcher, if you can show me where the port generation is done in the dotnet SDK, I would also appreciate it

**Comment by Tratcher** [comment]
File an issue in https://github.com/dotnet/sdk/ and we'll address it from there.

**Comment by sammychinedu2ky** [comment]
> File an issue in https://github.com/dotnet/sdk/ and we'll address it from there.

alright thanks

**Comment by sammychinedu2ky** [comment]
> if you can show me where the port generation is done in the dotnet SDK, I would also appreciate it

thanks done

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/sdk/issues/28265

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky  are you able to write a sample?

**Comment by sammychinedu2ky** [comment]
> @sammychinedu2ky are you able to write a sample?

Yh I was able to write one. And it has been merged

**Comment by Rick-Anderson** [comment]
> Yh I was able to write one. And it has been merged
@sammychinedu2ky  remind me where the code is at.

**Comment by sammychinedu2ky** [comment]
> > Yh I was able to write one. And it has been merged
> > @sammychinedu2ky  remind me where the code is at.

https://github.com/dotnet/AspNetCore.Docs.Samples/pull/80

**Comment by Rick-Anderson** [comment]
Fixed in #80
