### ISSUE TITLE
sample: Return multiple result types from minimal APIs

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs.Samples#77]
[Return multiple result types from minimal APIs](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#return-multiple-result-types-from-minimal-apis)

Possibly same code can do #76

**Comment by sammychinedu2ky** [comment]
Alright, @Rick-Anderson. 
Please where should it be located

**Comment by Rick-Anderson** [comment]
Create a folder in https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples

**Comment by Rick-Anderson** [comment]
Fixed in #80
