### ISSUE TITLE
app.MapPost("/fileUp", async (IFormFile file) 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs.Samples#8]
See https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-7-preview-1/
Put in https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples/IFormFile 
```
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.MapPost("/fileUp", async (IFormFile file) =>
{
    string tempfile = Path.GetTempFileName();
    using var stream = File.OpenWrite(tempfile);
    await file.CopyToAsync(stream);
});

app.MapPost("/FilesUp", async (IFormFileCollection myFiles) =>
{
    foreach (var file in myFiles)
    {
        string tempfile = Path.GetTempFileName();
        using var stream = File.OpenWrite(tempfile);
        await file.CopyToAsync(stream);
    }
});

app.Run();
```
Update readme.txt with instructions on testing.

**Comment by Rick-Anderson** [comment]
cc @sammychinedu2ky

**Comment by sammychinedu2ky** [comment]
ok on it

**Comment by sammychinedu2ky** [comment]
IFormFileCollection seems to work for me but IFormFile has issues binding data

**Comment by Rick-Anderson** [comment]
> IFormFileCollection seems to work for me but IFormFile has issues binding data

Call out that code when you create a PR and we'll have the experts review.

**Comment by sammychinedu2ky** [comment]
Alright thanks 🙌..

**Comment by Rick-Anderson** [comment]
It's done and documented [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0&branch=pr-en-us-26988#file-uploads-using-iformfile-and-iformfilecollection).

**Comment by sammychinedu2ky** [comment]
> It's done and documented [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0&branch=pr-en-us-26988#file-uploads-using-iformfile-and-iformfilecollection).

thanks
