### ISSUE TITLE
IResult implementation types are now publicly available

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs.Samples#92]
In [MinApiTestsSample](https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples/MinApiTestsSample), create at least one sample that uses the `IResult ` implementation types are **_now_** publicly available from [Improved unit testability for minimal route handlers](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-3/#improved-unit-testability-for-minimal-route-handlers)

@brunolins16 https://github.com/dotnet/aspnetcore/pull/40965 mentions all these `<HTTP Status>HttpResult` mentioned in the blog, but they're no longer in the source and I can't find a PR where they were renamed. The [history of Results.cs](https://github.com/dotnet/aspnetcore/commits/main/src/Http/Http.Results/src/Results.cs) doesn't make the renaming obvious. Please advise.

**Comment by brunolins16** [comment]
@Rick-Anderson  All HttpResults are now in the **.HttpResults namespace in this folder [HttpResults src](https://github.com/dotnet/aspnetcore/tree/main/src/Http/Http.Results/src) and they were moved to the new namespace, also some of them were renamed in this PR https://github.com/dotnet/aspnetcore/pull/41161.

I saw that the unit tests, in the sample, are already using the `HttpResults` types but in combination with `Results` static class, maybe we could add tests that use the [Interfaces](https://github.com/dotnet/aspnetcore/tree/main/src/Http/Http.Abstractions/src/HttpResults) when returning a `IResult` and add endpoints with `TypedResults` static class that return the concrete type, or maybe `Result<T1, TN>` and unit test for them.

**Comment by brunolins16** [comment]
Also, I have been working on https://github.com/dotnet/aspnetcore/issues/44258 that might cover some of this content.

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson please where should the sample code go to?

**Comment by Rick-Anderson** [comment]
> In [MinApiTestsSample](https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples/MinApiTestsSample), create at least one sample that uses the `IResult ` implementation types are **_now_** publicly available from [Improved unit testability for minimal route handlers](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-3/#improved-unit-testability-for-minimal-route-handlers)
> 

I think in n [MinApiTestsSample](https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples/MinApiTestsSample)

**Comment by Rick-Anderson** [comment]
Fixed in https://github.com/dotnet/AspNetCore.Docs.Samples/pull/115
